
#General settings
[general]
	#When enabled will log the memes executed. (Default: false)
	logTriggers = false
	#Setting to true allows for some of the questionable memes (Default: false)
	matureSounds = false
	#Use Minecraft's narrator to pronounce some copypasta memes (Default: false)
	useNarator = false
	#When enabled allows you to dig up memes in beaches. (Default: true)
	memesOnBeach = true

#Meme Settings
[meme]
	#Any meme id's added here will be removed from the possible meme list
	disabled_memes = []

